### ISSUE TITLE
Is it built in Qt?

### ISSUE THREAD

**Issue by shujaatak** [joshuawootonn/time-track#8]
I think you have shifted the development to electron and I wonder what kind of motivation you had to move to electron or problems you may had faced in Qt?

**Comment by joshuawootonn** [comment]
Hi @shujaatak! Sorry I haven't responded for so long. 

I chose Qt because my programming experience at the time was all in c++ and I didn't want to learn a new language. I then switched to Electron because my work was entirely on the web, and keeping up with the c++ community was difficult to do entirely in my free time.
